channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.3.2
  - pandas==2.3.1
  - scikit-learn==1.6.1
  - scipy==1.16.1
name: mlflow-env
